import = [
 "~/.config/alacritty/tokyonight.toml"
]

live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 750
unfocused_hollow = true

# Cursor style
style = { shape = "Underline", blinking = "Always" }  # Default: shape = "Block", blinking = "Off"

# Time after which cursor stops blinking, in seconds
blink_timeout = 5  # Default: 5

# Thickness of the cursor relative to the cell width
thickness = 0.05  # Default: 0.15

# Vi mode cursor style (falls back to the active value of the normal cursor if "None")
vi_mode_style = { shape = "Underline", blinking = "Always" }

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "VictorMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "VictorMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "VictorMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "VictorMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = -1

[[keyboard.bindings]]
chars = "#"
key = "Key3"
mods = "Alt"

[mouse]
hide_when_typing = false

[window]
decorations = "buttonless"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
